@startuml
participant main
participant fn_add_folder
database StructureInfo
database Foldar_A as A
database Foldar_B as B

activate main
main-->StructureInfo : フォルダ構成取得
main-->A : フォルダ構成チェック
opt フォルダ追加あり
main->fn_add_folder:追加対象のフォルダの情報
activate fn_add_folder
fn_add_folder-->B:追加対象のフォルダがあるか
opt 対象のフォルダがない場合
fn_add_folder-->B:追加対処のフォルダを追加する
end
fn_add_folder-->StructureInfo : フォルダ構成に追加対象のフォルダを追加
return 追加完了

deactivate fn_add_folder

end
deactivate main

@enduml