@startuml

participant コントローラ as ctrl
participant 同期処理 as sync

activate ctrl
ctrl --> sync : fn_sync_main
activate sync
sync --> sync : フォルダ構成の追加
activate sync
return 
sync --> sync : ファイル追加
activate sync
return 
sync --> sync : ファイル削除
activate sync
return 
sync --> sync : フォルダ削除
activate sync
return 
sync --> sync:ハッシュ値の更新

return 


@enduml