@startuml
participant main
participant fn_delete_file
database StructureInfo
database Foldar_TRASH as T
database Foldar_A as A
database Foldar_B as B

activate main
main-->StructureInfo : ファイル情報取得
main-->A : ファイル情報チェック
opt ファイル追加あり
main->fn_delete_file:削除対象のファイル情報
activate fn_delete_file
fn_delete_file --> B : 削除対象のファイルがあるか
alt 削除対象のファイルがある場合
fn_delete_file --> T : 削除対象のファイルを追加
fn_delete_file --> B : 削除対象のファイルを削除
fn_delete_file --> StructureInfo : 削除対象のファイル情報を削除
else ない場合
fn_delete_file --> StructureInfo : 削除対象のファイル情報を削除
end
return 
deactivate main

@enduml