@startuml
scale 700 width
start
:リポジトリ内のファイル一覧を取得;
while (リポジトリ内のすべてのファイルを確認したか?) is (no)
    :次のファイル(以降「対象ファイル」と呼ぶ)の情報を取得する;
    if(構成情報に対象ファイルと同じファイルパスの情報があるか？) then (yes)
        :見つかった構成情報(以降「対応構成情報」と呼ぶ)を取得する;
        if(対象ファイルのキャッシュ値と対応構成情報のキャッシュ値が同じであるか？) then (同じ)
        else (異なる)
            :もう片方のリポジトリから対象ファイルと同じファイルパスの
            ファイル(以降「対応ファイル」と呼ぶ)の情報を取得する;
            if(対応ファイルが存在するか?) then (yes)
                switch(対応ファイルのキャッシュ値)
                case (対象ファイルと同じ)
                    partition "**process** 構成情報更新"{
                        :対応構成情報のキャッシュ値を
                        対応ファイルのキャッシュ値に変更する;
                    }
                case (対応構成情報と同じ)
                    partition "**process** ファイル更新"{
                        :対象ファイルを削除する;
                        :対応ファイルをもう片方のリポジトリにコピーする;
                        :対応構成情報のキャッシュ値を
                        対応ファイルのキャッシュ値に変更する;
                    }
                case (どちらとも異なる)
                    partition "**process** コンフリクト発生"{
                        :コンフリクト情報に情報を追加する;
                    }
                endswitch
            else (no)
                partition "**process** ファイル追加"{
                    :対応ファイルをもう片方のリポジトリにコピーする;
                    :対応構成情報のキャッシュ値を
                    対応ファイルのキャッシュ値に変更する;
                }
            endif
        endif
    else (no)
        :もう片方のリポジトリから対象ファイルと同じファイルパスの
        ファイル(以降「対応ファイル」と呼ぶ)の情報を取得する;
            if(対応ファイルが存在するか?) then (yes)
                switch(対応ファイルのキャッシュ値)
                case (対象ファイルと同じ)
                    partition "**process**  "{
                        :対象ファイルの情報を構成情報に追加する;
                    }
                case (対象ファイルと異なる)
                    :コンフリクト情報に情報を追加する;
                endswitch
            else (no)
                :対応ファイルをもう片方のリポジトリにコピーする;
                :対象ファイルの情報を構成情報に追加する;
            endif
    endif
endwhile
stop
@enduml