@startuml
scale 700 width
start

partition "検出処理"{
    partition "サーバーリポジトリ走査"{
        :リポジトリを走査して**今回の構成情報**を取得;
        :構成情報ファイルから**前回の構成情報**を取得;
        :**前回の構成情報**と**今回の構成情報**を比較して**変更履歴**を取得;
        :**今回の構成情報**を書き出し;
        :**変更履歴**を書き出し; 
    }

    partition "クライアントリポジトリ走査"{
        :リポジトリを走査して**今回の構成情報**を取得;
        :構成情報ファイルから**前回の構成情報**を取得;
        :**前回の構成情報**と**今回の構成情報**を比較して**変更履歴**を取得;
        :**今回の構成情報**を書き出し;
        :**変更履歴**を書き出し; 
    }

    partition "差分確認"{
        :サーバーリポジトリの**構成情報**を読み出し;
        :クライアントリポジトリの**構成情報**を読み出し;
        :サーバーリポジトリとクライアントリポジトリの**構成情報**を比較して**差分情報**を取得;
        :**差分情報**を書き出し;
    }
}

partition "マージ処理"{
    :サーバーリポジトリの**変更履歴**を読み出し;
    :クライアントリポジトリの**変更履歴**を読み出し;
    :**差分情報**を読み出し;
    :マージ処理;
    :マージ後の**変更履歴**と**差分情報**を書き出し;
    :(TBD)**コンフリクト情報**の書き出し ;
}

partition "(TBD)コンフリクト処理"{
    :**コンフリクト情報**の読み出し。;
    :コンフリクト処理。;
    :**コンフリクト情報**の書き出し。;
}


stop
@enduml