@startuml
[コントローラ]
[同期処理]
[コンフリクト処理]
[通知処理]
[ファイル操作]
[構成情報操作]
[ハッシュ処理]

folder "クライアント" {
[写真フォルダー(client)]
[構成情報]
[コンフリクト情報]
[ログファイル]
[TRASH]
[config]
[ハッシュ値]
}
folder "ファイルサーバー"{
[写真フォルダー(server)]
}
[コントローラ] --> [同期処理] : 実行
[コントローラ] -->[コンフリクト処理] : 実行
[コントローラ] - [config] : 実行周期取得
[同期処理] --> [ファイル操作]
[同期処理] --> [構成情報操作]
[同期処理] -->[ハッシュ処理]
[コンフリクト処理] --> [構成情報操作]
[コンフリクト処理] --> [ファイル操作] : コピー/削除
[コンフリクト処理] --> [通知処理] : 通知
[コンフリクト処理] --> [ハッシュ処理]
[ファイル操作] --> [写真フォルダー(client)] : コピー/削除
[ファイル操作] --> [写真フォルダー(server)] : コピー/削除
[ファイル操作] --> [TRASH] : コピー
[ファイル操作] ..> [ログファイル] : ログ
[ファイル操作] - [config] : フォルダパス取得
[ハッシュ処理] --> [ハッシュ値]
[構成情報操作] --> [構成情報]
[構成情報操作] --> [コンフリクト情報]
[構成情報操作] ..> [ログファイル] : ログ
@enduml