@startuml
scale 700 width
node サーバー{
    folder リポジトリA{
        file サーバーファイル
    }

    frame アプリケーション{
        component MANAGEMENT
        component REPOSITORY
        component COMPOSITION
        component COMPOSITION_DIFF
        component MERGER
        component FILEOPERATER
    }

    frame 外部ファイル{
        file 設定情報
        file 構成情報
        file 変更履歴
        file コンフリクト情報
        file ログ
    }

    frame トラッシュフォルダ{
        file トラッシュファイル
    }
    
    frame OS{
        component shell
        component samba    
    }

}
node クライアント{
    folder リポジトリB{
        file クライアントファイル
    }
}

MANAGEMENT --> REPOSITORY
MANAGEMENT --> MERGER
REPOSITORY --> COMPOSITION
REPOSITORY --> COMPOSITION_DIFF
COMPOSITION --> FILEOPERATER
MERGER --> FILEOPERATER

MANAGEMENT --> 設定情報
REPOSITORY --> 構成情報
REPOSITORY --> 変更履歴
MERGER --> コンフリクト情報
FILEOPERATER --> ログ
FILEOPERATER --> OS
OS --> リポジトリA
OS --> リポジトリB
OS --> トラッシュフォルダ



@enduml