@startuml
scale 700 width
node サーバー{
    folder リポジトリA{
        file サーバーファイル
    }

    frame アプリケーション{
        component MNG
        component SYNC
        component NOTICE
        component DATA
        component CMD
        component CONFLICT
    }

    frame 外部ファイル{
        file 設定情報
        file 構成情報
        file コンフリクト情報
        file ログ
    }

    frame トラッシュフォルダ{
        file トラッシュファイル
    }
    
    frame OS{
        component scheduler
        component shell
        component toast
        interface samba    
    }

}
node クライアント{
    folder リポジトリB{
        file クライアントファイル
    }
}

scheduler --> MNG
MNG --> SYNC
MNG --> NOTICE
MNG --> CONFLICT
SYNC --> CMD
SYNC --> DATA
CONFLICT --> DATA
MNG --> DATA 
DATA --> 外部ファイル
CMD --> shell
NOTICE --> toast
shell --> リポジトリA
shell -- samba
shell --> トラッシュフォルダ
samba --> リポジトリB

@enduml